graph LR
  User[Usuário (Navegador)] -->|HTTP| NodePort[Service NodePort<br/>frontend-svc:30080<br/>ns: frontend]
  subgraph ns: frontend
    NodePort --> FE[Deployment frontend-deploy<br/>replicas: 3]
  end

  FE -->|HTTP:3000| SVCBE[Service ClusterIP<br/>backend-svc:3000<br/>ns: backend]

  subgraph ns: backend
    SVCBE --> BE[Deployment backend-deploy<br/>replicas: 2]
  end

  BE -->|TCP:5432| SVCDb[Service ClusterIP<br/>db-svc:5432<br/>ns: database]

  subgraph ns: database
    SVCDb --> DB[(Deployment db-deploy<br/>replicas: 1)]
    DB --- PVC[(PVC)]
    PVC --- PV[(PV)]
    DB:::store
  end

classDef store fill:#eef,stroke:#333,stroke-width:1px;